[workspace]
authors = ["Leon Welchert <lichturm@posteo.de>"]
channels = ["conda-forge"]
name = "aider"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
aider-install = ">=0.2.0, <0.3"
